# Generated by Django 2.2.4 on 2019-10-06 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pushed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, upload_to='file_images'),
        ),
    ]
